repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.350
    hooks:
      - id: pyright
  - repo: https://github.com/pre-commit/mirrors-lizard
    rev: v1.17.10
    hooks:
      - id: lizard
        args: ["-C", "5", "-L", "25", "-a", "4"]
  - repo: https://github.com/import-linter/import-linter
    rev: v2.1
    hooks:
      - id: import-linter
  - repo: local
    hooks:
      - id: contract-validation
        name: Service contract validation
        entry: .venv/bin/python -m src.utils.validate_contract
        language: system
        pass_filenames: false

      - id: duplicate-values
        name: Duplicate value check
        entry: .venv/bin/python -m src.utils.validate_no_duplicates
        language: system
        pass_filenames: false
