- name: Provision storage
  hosts: all
  tasks:
    - name: Create volume directories
      ansible.builtin.file:
        path: "{{ item.1.path }}"
        state: directory
        owner: "{{ item.0.uid }}"
        mode: "{{ item.1.mode }}"
      loop: "{{ manifests | subelements('volumes') }}"
